import { useEffect } from "react";
import { Link } from "react-router-dom";

const CONTACT_EMAIL = "support@andamanbazaar.in";
const LAST_UPDATED = "19 May 2026";

const EditorialPolicy = () => {
  useEffect(() => {
    document.title = "Editorial & Copyright Policy · AndamanBazaar";
    const meta =
      document.querySelector('meta[name="description"]') ??
      Object.assign(document.createElement("meta"), { name: "description" });
    meta.setAttribute(
      "content",
      "How AndamanBazaar sources, rewrites, attributes, and verifies news and blog content — our copyright, fair-use, and takedown policy.",
    );
    if (!meta.parentNode) document.head.appendChild(meta);
  }, []);

  return (
    <section className="prose prose-slate max-w-none py-8 dark:prose-invert">
      <h1>Editorial &amp; Copyright Policy</h1>
      <p className="text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>

      <p>
        AndamanBazaar publishes two kinds of editorial content on its blog: <strong>news rewrites</strong> sourced from
        publicly available reporting about the Andaman &amp; Nicobar Islands, and <strong>evergreen travel guides</strong>{" "}
        written from general, widely-known information about the islands. This page explains how we produce that content
        and how we respect the copyright of the publications we read.
      </p>

      <h2>What we believe</h2>
      <ul>
        <li>
          <strong>Facts aren&rsquo;t copyrightable, but prose is.</strong> We report the facts of a story — who, what,
          when, where — and write our own sentences around them.
        </li>
        <li>
          <strong>Credit the original reporter.</strong> Every news post on AndamanBazaar names the source publication in
          the body of the article and links back to the original story at the bottom under a <em>Source</em> section.
        </li>
        <li>
          <strong>Quotation is limited.</strong> We use direct quotes only when a named person (an official, witness, or
          spokesperson) is speaking, keep each quote short (under ~25 words), and clearly attribute it.
        </li>
        <li>
          <strong>No copied images.</strong> Cover images on news and blog posts are generated by our own AI pipeline and
          stored in our own bucket. We do not reproduce photos, captions, or infographics from source publications.
        </li>
      </ul>

      <h2>How news posts are produced</h2>
      <ol>
        <li>
          Our automated news agent checks a small, curated list of public Andaman news pages once a day and lists their
          recent headlines.
        </li>
        <li>
          Before fetching any page, the agent reads that site&rsquo;s <code>robots.txt</code> and skips any URL the
          publisher has marked as <em>Disallow</em> for general crawlers.
        </li>
        <li>
          Our crawler identifies itself honestly as <code>AndamanBazaarBot</code> with a contact URL, so publishers can
          block us at any time.
        </li>
        <li>
          A short extract of the article (capped at a few thousand characters) is passed to a large language model. The
          model is instructed to <strong>paraphrase</strong> the facts in its own words, attribute the source in-body,
          and never reproduce the publisher&rsquo;s sentences or paragraph structure.
        </li>
        <li>
          The resulting draft is validated, de-duplicated against our last 20 published posts, and only then published
          with the original source URL clearly linked.
        </li>
      </ol>

      <h2>How evergreen blog posts are produced</h2>
      <p>
        Travel guides on AndamanBazaar are written from general knowledge about geography, climate, and culture of the
        islands. We do not lift copy from guidebooks, government brochures, hotel websites, or other travel blogs. We
        avoid naming individual private operators by brand so that we don&rsquo;t accidentally echo their marketing
        copy.
      </p>

      <h2>Takedown &amp; correction requests</h2>
      <p>
        If you are a rights-holder (or represent one) and you believe a post on AndamanBazaar reproduces your work in a
        way you are not comfortable with, please email{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> with:
      </p>
      <ul>
        <li>the URL of the AndamanBazaar post in question;</li>
        <li>the URL of the original work and proof you hold or represent the rights;</li>
        <li>the specific passage or element you&rsquo;d like removed or further attributed.</li>
      </ul>
      <p>
        We aim to respond within 5 business days and will remove, rewrite, or strengthen attribution on legitimate
        requests — usually within 48 hours of confirming the claim.
      </p>

      <h2>Block our crawler</h2>
      <p>
        If you do not want your site to appear in our news rewrites, add the following to your <code>robots.txt</code>:
      </p>
      <pre>
        <code>{`User-agent: AndamanBazaarBot\nDisallow: /`}</code>
      </pre>
      <p>Our agent will respect this on its next run.</p>

      <p className="text-sm text-muted-foreground">
        Questions about anything on this page? See our <Link to="/terms">Terms</Link> or write to{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </section>
  );
};

export default EditorialPolicy;